# 2.7 How handle Exceptions 

## Example Code

```dart
void main(){
  String name = "Dart";

  try{
    print ('Name: $name');

    // The following line generates a RangeError
    name.indexOf(name[0], name.length - (name.length+2));
  } catch (exception) {
    print ('Exception: $exception');
  } finally {
    print ('Mission completed!');
  }
}
```
 
## Example Output:

The result of the print statement is shown below:

```dart
Name: Dart
Exception: RangeError: Invalid value: Not in inclusive range 0..4: -2
Mission completed!
```

